name: Build and deploy site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        run: |
          cd site
          quarto render

      - name: Add CNAME to output
        run: |
          echo "npsweeney.co.uk" > site/_site/CNAME

      - name: Deploy to main
        uses: peaceiris/actions-main@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: site/_site
          force_orphan: true
